name: Can release

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  can_release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - id: check-release
        run: |
          if [[ $(git show --no-patch --format=%s) =~ ^v[0-9]+\.[0-9]+\.[0-9]$ ]]; then
            echo ::set-output name=IS_PUBLISH::true
          fi
      - if: steps.check-release.outputs.IS_PUBLISH != 'true'
        uses: andymckay/cancel-action@0.2
      - run: yarn install --ignore-script --frozen-lockfile
      - run: yarn run can-npm-publish
