name: Can release

on:
  repository_dispatch:
    types: 
      - can-release

jobs:
  can_release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn install --ignore-script --frozen-lockfile
      - run: yarn run can-npm-publish
